config/routes.rb
Rails.application.routes.draw do
  get 'borrowed_items/index'

  unauthenticated :user do
    devise_scope :user do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  authenticated :user do
    root to: 'borrowed_items#index'
  end

  get 'profile', to: 'users#show', as: 'profile'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  put 'profile/update', to: 'users#update', as: 'update_profile'

  get 'borrowed_items', to: 'borrowed_items#index', as: 'borrowed_items'
  post 'borrow/:id', to: 'borrowed_items#borrow', as: 'borrow'
  post 'return/:id', to: 'borrowed_items#return', as: 'return'

  resources :users, except: [:destroy, :create]

  resources :items
  resources :cupboards, except: :show

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
end

app/models/cupboard.rb
# == Schema Information
#
# Table name: cupboards
#
#  created_at  :datetime         not null
#  description :text
#  id          :integer          not null, primary key
#  name        :string
#  updated_at  :datetime         not null
#

class Cupboard < ActiveRecord::Base
  has_many :items
end

app/controllers/cupboards_controller.rb
# == Schema Information
#
# Table name: cupboards
#
#  created_at  :datetime         not null
#  description :text
#  id          :integer          not null, primary key
#  name        :string
#  updated_at  :datetime         not null
#

class CupboardsController < ApplicationController
  before_action :ensure_officer
  before_action :set_cupboard, only: [:edit, :update, :destroy]

  # GET /cupboards
  def index
    @cupboards = Cupboard.all
  end

  # GET /cupboards/new
  def new
    @cupboard = Cupboard.new
  end

  # GET /cupboards/1/edit
  def edit
  end

  # POST /cupboards
  def create
    @cupboard = Cupboard.new(cupboard_params)

    if @cupboard.save
      redirect_to cupboards_url, notice: 'Cupboard was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cupboards/1
  def update
    if @cupboard.update(cupboard_params)
      redirect_to cupboards_url, notice: 'Cupboard was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cupboards/1
  def destroy
    @cupboard.destroy
    redirect_to cupboards_url, notice: 'Cupboard was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cupboard
      @cupboard = Cupboard.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cupboard_params
      params.require(:cupboard).permit(:name, :description)
    end
end

app/helpers/cupboards_helper.rb
# == Schema Information
#
# Table name: cupboards
#
#  created_at  :datetime         not null
#  description :text
#  id          :integer          not null, primary key
#  name        :string
#  updated_at  :datetime         not null
#

module CupboardsHelper
end

app/views/cupboards/_form.html.erb
<%= form_for(@cupboard) do |f| %>
  <% if @cupboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cupboard.errors.count, "error") %> prohibited this cupboard from being saved:</h2>

      <ul>
      <% @cupboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Name: <%= f.text_field :name %>
  </label>

  <%= f.submit 'Create', class: 'button' %>
<% end %>

app/views/cupboards/edit.html.erb
<h4>Editing Cupboard</h4>

<hr>

<%= render 'form' %>

app/views/cupboards/index.html.erb
<% content_for :title, 'Cupboards' %>
<p id="notice"><%= notice %></p>

<h4>
  Cupboards
  <small> <%= link_to 'NEW', new_cupboard_path, class: 'success label' %></small>
</h4>

<hr>

<table>
  <thead>
    <tr>
      <th width="200">Name</th>
      <th width="150"></th>
    </tr>
  </thead>

  <tbody>
    <% @cupboards.each do |cupboard| %>
      <tr>
        <td><%= cupboard.name %></td>
        <td>
          <%= link_to 'Edit', edit_cupboard_path(cupboard), class: 'warning label' %>
          <%= link_to 'Destroy', cupboard, method: :delete, data: { confirm: 'Are you sure?' }, class: 'alert label' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cupboards/new.html.erb
<h4>New Cupboard</h4>

<hr>

<%= render 'form' %>