config/routes.rb
Rails.application.routes.draw do
  get 'borrowed_items/index'

  unauthenticated :user do
    devise_scope :user do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  authenticated :user do
    root to: 'borrowed_items#index'
  end

  get 'profile', to: 'users#show', as: 'profile'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  put 'profile/update', to: 'users#update', as: 'update_profile'

  get 'borrowed_items', to: 'borrowed_items#index', as: 'borrowed_items'
  post 'borrow/:id', to: 'borrowed_items#borrow', as: 'borrow'
  post 'return/:id', to: 'borrowed_items#return', as: 'return'

  resources :users, except: [:destroy, :create]

  resources :items
  resources :cupboards, except: :show

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  active                 :boolean
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  id                     :integer          not null, primary key
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  sign_in_count          :integer          default(0), not null
#  uid                    :string
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  before_create :generate_uid
  before_validation :set_default_role, on: :create
  before_validation :set_default_account_status, on: :create

  ROLES = %w{
    Borrower
    Officer
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :borrowed_items
  has_many :items, through: :borrowed_items

  validates :role, presence: true, inclusion: { in: ROLES }
  validates_uniqueness_of :uid

  scope :recent, -> { order(updated_at: :desc) }
  scope :borrowers, -> { where(role: "Borrower") }

  ROLES.each do |role|
    define_method "#{role.downcase}?".to_sym do
      self.role == role
    end
  end

  def name
    "#{first_name.strip} #{last_name.strip}"
  end

  def borrowed_fixed_assets
    borrowed_items.map { |bi| bi if bi.fixed_asset? && !bi.returned? }.flatten.compact
  end

  def total_fines
    fines = 0
    borrowed_fixed_assets.map { |bi| fines += bi.fine if bi.due? && bi.fined? }.flatten.compact
    fines
  end

  def fined?
    self.total_fines > 0
  end

  def borrow item
    borrowed_item = BorrowedItem.new(item_id: item.id, user_id: self.id)
    borrowed_item.save
    item.decrement!(:quantity, 1)
  end

  def return borrowed_item
    return false unless borrowed_item
    if borrowed_item.fined?
      borrowed_item.remove_fine_and_return!
    else
      borrowed_item.return!
    end
    borrowed_item.item.increment!(:quantity, 1)
  end

  private
  def set_default_account_status
    self.active = true
  end

  def set_default_role
    self.role = "Borrower"
  end

  def generate_uid
    self.uid = loop do
      random_token = SecureRandom.hex(16)
      break random_token unless self.class.exists?(uid: random_token)
    end
  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  active                 :boolean
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  id                     :integer          not null, primary key
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  sign_in_count          :integer          default(0), not null
#  uid                    :string
#  updated_at             :datetime         not null
#

class UsersController < ApplicationController
  before_action :ensure_officer, only: :index
  before_action :set_user, only: [:show, :edit, :update]

  # GET /users
  def index
    @users = User.recent.borrowers
  end

  # GET /users/1
  def show
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      redirect_to profile_url, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = params[:id].present? ? User.find(params[:id]) : current_user
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :active)
    end
end

app/helpers/users_helper.rb
# == Schema Information
#
# Table name: users
#
#  active                 :boolean
#  created_at             :datetime         not null
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  id                     :integer          not null, primary key
#  last_name              :string
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :string
#  sign_in_count          :integer          default(0), not null
#  uid                    :string
#  updated_at             :datetime         not null
#

module UsersHelper
  def dynamic_edit_user_link
    if params[:id].present?
      link_to 'Edit', edit_user_path(@user), class: 'button'
    else
      link_to 'Edit', edit_profile_path, class: 'button'
    end
  end

  def account_status user
    user.active? ? 'Active' : 'Deactivated'
  end
end

app/views/users/edit.html.erb
<h4>Editing User</h4>

<hr>

<%= form_for @user, url: update_profile_path, method: :put do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <label>
    E-mail Address: <%= f.text_field :email %>
  </label>

  <label>
    First Name: <%= f.text_field :first_name %>
  </label>

  <label>
    Last Name: <%= f.text_field :last_name %>
  </label>

  <label>
    Password: <%= f.password_field :password %>
  </label>

  <label>
    Password: <%= f.password_field :password_confirmation %>
  </label>

  <% if current_user.officer? %>
    <label>
      Active: <%= f.select :active, [:true, :false].map { |a| [a.to_s.capitalize, a]} %>
    </label>
  <% end %>

  <%= f.submit 'Update', class: 'button' %>
<% end %>

app/views/users/index.html.erb
<% content_for :title, 'Borrowers' %>
<p id="notice"><%= notice %></p>

<h4>
  Borrowers
</h4>

<hr>

<table>
  <thead>
    <tr>
      <th width="100">E-mail</th>
      <th width="250">Name</th>
      <th width="100">Acct Status</th>
      <th width="150"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= account_status user %></td>
        <td>
          <%= link_to 'Show', user, class: 'label' %>
          <%= link_to 'Edit', edit_user_path(user), class: 'warning label' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<% content_for :title, "Borrower Details" %>
<p id="notice"><%= notice %></p>

<h4>
  Borrower Details
</h4>

<hr>

<label>
  Name: <%= @user.name %>
</label>

<label>
  E-mail: <%= @user.email %>
</label>

<label>
  Acct Status: <%= account_status @user %>
</label>

<label>
  Fines: <%= @user.fined? ? @user.total_fines : "No existing fines" %>
</label>

<br>

<h5>
  Borrower's Item History
</h5>
<hr>

<%= render partial: 'borrowed_items/tabs',
            locals: { fixed_assets: @user.borrowed_items.latest_fixed_assets,
                       consumables: @user.borrowed_items.latest_consumables } %>

<%= dynamic_edit_user_link %>