config/routes.rb
Rails.application.routes.draw do
  get 'borrowed_items/index'

  unauthenticated :user do
    devise_scope :user do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  authenticated :user do
    root to: 'borrowed_items#index'
  end

  get 'profile', to: 'users#show', as: 'profile'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  put 'profile/update', to: 'users#update', as: 'update_profile'

  get 'borrowed_items', to: 'borrowed_items#index', as: 'borrowed_items'
  post 'borrow/:id', to: 'borrowed_items#borrow', as: 'borrow'
  post 'return/:id', to: 'borrowed_items#return', as: 'return'

  resources :users, except: [:destroy, :create]

  resources :items
  resources :cupboards, except: :show

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
end

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to 'Research Bods', root_path %>
      </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">

      <% if user_signed_in? %>

        <li class="has-dropdown">
          <%= link_to "#{current_user.email}", profile_path %>
          <ul class="dropdown">
            <li>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>

      <% else %>

        <li>
          <%= link_to 'Log in', root_path %>
        </li>

      <% end %>
    </ul>

  </section>
</nav>

app/views/shared/_sidebar.html.erb
<ul class="side-nav">
  <% if current_user.officer? %>
    <li>
      <%= link_to 'Borrowers', users_path %>  
    </li>
    <li>
      <%= link_to 'Cupboards', cupboards_path %>
    </li>
    <li>
      <%= link_to 'Items', items_path %>
    </li>
  <% end %>
  <li>
    <%= link_to dynamic_borrowed_items_label, borrowed_items_path %>
  </li
</ul>