config/routes.rb
Rails.application.routes.draw do
  get 'borrowed_items/index'

  unauthenticated :user do
    devise_scope :user do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  authenticated :user do
    root to: 'borrowed_items#index'
  end

  get 'profile', to: 'users#show', as: 'profile'
  get 'profile/edit', to: 'users#edit', as: 'edit_profile'
  put 'profile/update', to: 'users#update', as: 'update_profile'

  get 'borrowed_items', to: 'borrowed_items#index', as: 'borrowed_items'
  post 'borrow/:id', to: 'borrowed_items#borrow', as: 'borrow'
  post 'return/:id', to: 'borrowed_items#return', as: 'return'

  resources :users, except: [:destroy, :create]

  resources :items
  resources :cupboards, except: :show

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  created_at   :datetime         not null
#  cupboard_id  :integer
#  description  :string
#  id           :integer          not null, primary key
#  item_type    :integer
#  name         :string
#  product_code :string
#  quantity     :integer
#  updated_at   :datetime         not null
#

class Item < ActiveRecord::Base
  belongs_to :cupboard
  has_many :borrowed_items
  has_many :borrowers, through: :borrowed_items, source: :user

  enum item_type: [:fixed_asset, :consumable]

  validates :item_type, inclusion: { in: Item.item_types.keys }

  scope :recent, -> { order(created_at: :desc) }
  scope :by_name, -> { order(name: :asc) }
  scope :fixed_assets, -> { where(item_type: "fixed_asset") }
  scope :consumables, -> { where(item_type: "consumable") }
  scope :by_cupboard, -> { order(cupboard_id: :asc) }

  def out_of_stock?
    self.quantity == 0 ? true : false
  end
end

app/controllers/items_controller.rb
# == Schema Information
#
# Table name: items
#
#  created_at   :datetime         not null
#  cupboard_id  :integer
#  description  :string
#  id           :integer          not null, primary key
#  item_type    :integer
#  name         :string
#  product_code :string
#  quantity     :integer
#  updated_at   :datetime         not null
#

class ItemsController < ApplicationController
  before_action :ensure_officer
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.by_name
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to items_url, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to items_url, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:name, :description, :cupboard_id, :quantity, :item_type, :product_code)
    end
end

app/helpers/items_helper.rb
# == Schema Information
#
# Table name: items
#
#  created_at   :datetime         not null
#  cupboard_id  :integer
#  description  :string
#  id           :integer          not null, primary key
#  item_type    :integer
#  name         :string
#  product_code :string
#  quantity     :integer
#  updated_at   :datetime         not null
#

module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label>
    Name: <%= f.text_field :name %>
  </label>

  <label>
    Description: <%= f.text_area :description %>
  </label>

  <label>
    Quantity: <%= f.text_field :quantity %>
  </label>

  <label>
    Item Type: <%= f.select :item_type, Item.item_types.keys.map {|k| [k.titleize, k] } %>
  </label>

  <label>
    Product Code: <%= f.text_field :product_code %>
  </label>

  <label>
    Cupboard:
    <%= f.select :cupboard_id, Cupboard.all.map { |c| ["#{c.name}", c.id]} %>
  </label>

  <%= f.submit 'Create', class: 'button' %>
<% end %>

app/views/items/_history.html.erb
<table>
  <thead>
    <tr>
      <th width="200">Borrowed by</th>
      <th width="200">Borrowed at</th>
      <th width="200">Due on</th>
      <%= '<th width="200">Returned at</th>'.html_safe if @item.fixed_asset? %>
    </tr>
  </thead>

  <tbody>
    <% borrowed_items.each do |borrowed_item| %>
      <tr>
        <td><%= borrowed_item.user.name %></td>
        <td><%= borrowed_item.borrowed_at.strftime("%b %e, %Y") %> </td>
        <td><%= borrowed_item.due_on.strftime("%b %e, %Y")%></td>
        <%= "<td>#{dynamic_returned_at_value borrowed_item}</td>".html_safe if borrowed_item.fixed_asset? %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/edit.html.erb
<h4>Editing Item</h4>

<hr>

<%= render 'form' %>

app/views/items/index.html.erb
<% content_for :title, 'Items' %>
<p id="notice"><%= notice %></p>

<h4>
  Items
  <small> <%= link_to 'NEW', new_item_path, class: 'success label' %></small>
</h4>

<hr>
<table>
  <thead>
    <tr>
      <th width="100">Code</th>
      <th width="200">Name</th>
      <th width="100">Quantity</th>
      <th width="100">Type</th>
      <th width="200"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product_code %></td>
        <td><%= item.name %></td>
        <td><%= item.quantity %> </td>
        <td><%= item.item_type.titleize %></td>
        <td>
          <%= link_to 'Show', item, class: 'label' %>
          <%= link_to 'Edit', edit_item_path(item), class: 'warning label' %>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'alert label' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<h4>New Item</h4>

<hr>

<%= render 'form' %>

app/views/items/show.html.erb
<% content_for :title, 'Item Details' %>
<p id="notice"><%= notice %></p>

<h4>
  Item Details
</h4>
<hr>

<label>
  Cupboard: <%= @item.cupboard.name %>
</label>

<label>
  Name: <%= @item.name %>
</label>

<label>
  Item Type: <%= @item.item_type.titleize %>
</label>

<label>
  Quantity: <%= @item.quantity %>
</label>

<label>
  Product Code: <%= @item.product_code %>
</label>
<hr>
<label>
  Description: <br>
  <%= @item.description %>
</label>

<br>

<h5>
  Item History
</h5>
<hr>

<%= render partial: 'history', locals: { borrowed_items: @item.borrowed_items.recently_updated } %>